# Generated by Django 5.1.6 on 2025-02-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_user_alter_notes_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
